[package]
name = "krita_bevy_anim"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = [ "derive" ] }
anyhow = "1.0"
image = "0.24"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
